import React from "react";
import Head from 'next/head';

import NavBar from "./components/Navbar/NavBar";
import Hero from './components/Hero/Hero';
import SepLine from './components/SepLine/SepLine'
import About from './components/AboutMe/About'
import ContactMe from './components/ContactMe/ContactMe'
import Footer from './components/Footer/Footer'
import MainSkillset from './components/MainSkillset/MainSkillset'
import Skills from './components/Skills/Skills'
import SomeProjects from './components/SomeProjects/SomeProjects'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <nav>
        <NavBar />

      </nav>
      <main className={styles.main}>
        <Hero/>
        <SepLine/>
        <About/>
        <MainSkillset/>
        <SomeProjects/>
        <Skills/>
        <ContactMe/>
        <Footer/> 
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
